# Generated by Django 5.1 on 2024-08-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens_venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvenda',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
