# Generated by Django 5.1 on 2024-08-19 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('venda', '0001_initial'),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_venda', to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_venda', to='vendedor.vendedor'),
            preserve_default=False,
        ),
    ]
