# Generated by Django 5.1 on 2024-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_venda_cliente_venda_total_a_pagar_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='venda_numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
