# Generated by Django 5.1 on 2024-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_venda_venda_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='venda_numero',
            field=models.IntegerField(unique=True),
        ),
    ]
