# Generated by Django 5.1 on 2024-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_alter_venda_venda_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(),
        ),
    ]
