# Generated by Django 5.1 on 2024-08-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_alter_venda_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='venda_numero',
        ),
    ]
