services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - app

  app:
    build: .
    image: devpro-rest:dev
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corpsystem
      MYSQL_USER: corpsystem
      MYSQL_PASSWORD: corpsystem
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: