# Generated by Django 5.1 on 2024-08-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_remove_categoria_produto'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='categoria.categoria'),
            preserve_default=False,
        ),
    ]
